# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()

a1 = np.array([1, 2, 3])
# Create a 2-dimensional NumPy array using np.array()

a2 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((3, 3), 2, dtype('int32'), 9, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2,
                 index=["Age", "Sex", "Height"],
                 columns=["Person1", "Person2","Person3"])
df

Person1  Person2  Person3
Age           1        2        3
Sex           4        5        6
Height        7        8        9

In [8]:
# Create an array of shape (10, 2) with only ones
ar1 = np.ones((10, 2))
ar1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
# Create an array within a range of 0 and 100 with step 3
arr3 = np.arange(0, 100, 3)
arr3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [12]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr4 = np.random.randint(10, size=(7,2))
arr4

array([[7, 7],
       [5, 0],
       [4, 8],
       [1, 4],
       [4, 2],
       [0, 3],
       [8, 6]])

In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr5 = np.random.random(size=(3, 5))
arr5

array([[0.87619843, 0.59210754, 0.31969355, 0.42650097, 0.2805016 ],
       [0.98951647, 0.59560656, 0.01276035, 0.11516848, 0.86366824],
       [0.38486479, 0.48174   , 0.85895936, 0.77781487, 0.45938632]])

In [17]:
# Set the random seed to 42

np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
arr6 = np.random.randint(10, size=(4, 6))
arr6

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [20]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr7 = np.random.randint(10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(arr7)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [24]:
arr7

array([[3, 7, 6, 8, 7, 4, 1],
       [4, 7, 9, 8, 8, 0, 8],
       [6, 8, 7, 0, 7, 7, 2]])

In [21]:
# Find the 0'th index of the latest array you created
arr7[0]

array([3, 7, 6, 8, 7, 4, 1])

In [23]:
# Get the first 2 rows of latest array you created
arr7[:2]

array([[3, 7, 6, 8, 7, 4, 1],
       [4, 7, 9, 8, 8, 0, 8]])

In [25]:
# Get the first 2 values of the first 2 rows of the latest array
arr7[:2,:2]

array([[3, 7],
       [4, 7]])

In [30]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr8 = np.random.randint(10, size=(3, 5))
arr9 = np.ones((3, 5))
arr8

array([[2, 5, 1, 9, 8],
       [4, 5, 3, 9, 6],
       [8, 6, 0, 0, 8]])

In [33]:
# Add the two arrays together
arz = arr8 + arr9

In [34]:
# Create another array of ones of shape (5, 3)
arr10 = np.ones((5, 3))

In [35]:
# Try add the array of ones and the other most recent array together
arz + arr10

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [36]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3, 5))

In [37]:
# Subtract the new array of ones from the other most recent array
arz - ones

array([[2., 5., 1., 9., 8.],
       [4., 5., 3., 9., 6.],
       [8., 6., 0., 0., 8.]])

In [38]:
# Multiply the ones array with the latest array
arz * ones

array([[ 3.,  6.,  2., 10.,  9.],
       [ 5.,  6.,  4., 10.,  7.],
       [ 9.,  7.,  1.,  1.,  9.]])

In [39]:
# Take the latest array to the power of 2 using '**'
arz ** 2

array([[  9.,  36.,   4., 100.,  81.],
       [ 25.,  36.,  16., 100.,  49.],
       [ 81.,  49.,   1.,   1.,  81.]])

In [40]:
# Do the same thing with np.square()
np.square(arz)

array([[  9.,  36.,   4., 100.,  81.],
       [ 25.,  36.,  16., 100.,  49.],
       [ 81.,  49.,   1.,   1.,  81.]])

In [42]:
# Find the mean of the latest array using np.mean()
arz.mean()

5.933333333333334

In [43]:
# Find the maximum of the latest array using np.max()
np.max(arz)

10.0

In [44]:
# Find the minimum of the latest array using np.min()
np.min(arz)

1.0

In [45]:
# Find the standard deviation of the latest array
np.std(arz)

3.0652170486860397

In [46]:
# Find the variance of the latest array
np.var(arz)

9.395555555555555

In [47]:
# Reshape the latest array to (3, 5, 1)
arz.reshape((3, 5, 1))

array([[[ 3.],
        [ 6.],
        [ 2.],
        [10.],
        [ 9.]],

       [[ 5.],
        [ 6.],
        [ 4.],
        [10.],
        [ 7.]],

       [[ 9.],
        [ 7.],
        [ 1.],
        [ 1.],
        [ 9.]]])

In [48]:
# Transpose the latest array
arz.T

array([[ 3.,  5.,  9.],
       [ 6.,  6.,  7.],
       [ 2.,  4.,  1.],
       [10., 10.,  1.],
       [ 9.,  7.,  9.]])

What does the transpose do?

In [49]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ara1 = np.random.randint(10, size=(3, 3))
ara2 = np.random.randint(10, size=(3, 2))

In [51]:
# Perform a dot product on the two newest arrays you created

np.dot(ara1, ara2)

array([[67, 93],
       [79, 81],
       [92, 98]])

In [52]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ara3 = np.random.randint(10, size=(4, 3))
ara4 = np.random.randint(10, size=(4, 3))

In [53]:
# Perform a dot product on the two newest arrays you created
ara3.dot(ara4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [54]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
ara3.dot(ara4.T)

array([[56, 11, 60,  6],
       [ 0, 24, 36, 21],
       [42, 17, 40,  4],
       [ 0,  4, 16,  8]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [55]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ara5 = np.random.randint(10, size=(5, 2))
ara6 = np.random.randint(10, size=(5, 2))

In [57]:
ara5

array([[4, 9],
       [5, 6],
       [3, 6],
       [7, 0],
       [5, 7]])

In [58]:
ara6

array([[4, 3],
       [1, 5],
       [5, 0],
       [8, 5],
       [2, 3]])

In [56]:
# Compare the two arrays with '>'
ara5 > ara6

array([[False,  True],
       [ True,  True],
       [False,  True],
       [False, False],
       [ True,  True]])

What happens when you compare the arrays with `>`?

In [59]:
# Compare the two arrays with '>='
ara5 >= ara6

array([[ True,  True],
       [ True,  True],
       [False,  True],
       [False, False],
       [ True,  True]])

In [60]:
# Find which elements of the first array are greater than 7
ara5 > 7

array([[False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [61]:
# Which parts of each array are equal? (try using '==')
ara5 == ara6

array([[ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [63]:
# Sort one of the arrays you just created in ascending order
ara5.sort()
ara5

array([[4, 9],
       [5, 6],
       [3, 6],
       [0, 7],
       [5, 7]])

In [66]:
# Sort the indexes of one of the arrays you just created
ara5.argsort()


array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1]], dtype=int64)

In [69]:
# Find the index with the maximum value in one of the arrays you've created
ara5.argmax(axis=0)

array([1, 0], dtype=int64)

In [70]:
# Find the index with the minimum value in one of the arrays you've created
ara5.argmin(axis=1)

array([0, 0, 0, 0, 0], dtype=int64)

In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [72]:
# Create an array of normally distributed random numbers
arnorm = np.random.randn(10)
arnorm

array([ 1.16920765,  0.87331697,  0.20565013, -1.44348335, -1.02771086,
        0.74124064, -1.71052958,  0.11897849,  1.00048561,  0.15242086])

In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100
areven = np.linspace()

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.